name: Mineground
main: com.mineground.Mineground
version: 2.0
website: mineground.com
author: LVM Development Team

# Permission descriptions for the various features implemented in Mineground.
permissions:
    # ----------------------------------------------------------------------------------------------
    # Permission groups
    # ----------------------------------------------------------------------------------------------
    mineground.guest:
        description: All permissions available for guests.
        children:
            # Permissions to grant to all the players:
            command.report: true
            command.spawn: true
    mineground.builder:
        description: All permission available for builders.
        children:
            mineground.guest: true
            # Permissions to grant to builders:
            command.classic: true
            command.creative: true
            command.pm: true
            command.reply: true
            command.survival: true
            warp.create: true
            warp.teleport: true
            warp.remove: true
    mineground.sbuilder:
        description: All permissions available for sbuilders.
        children:
            mineground.builder: true
            # Permissions to grant to super-builders:
            command.fly: true
    mineground.vip:
        description: All permissions available for VIPs.
        children:
            mineground.sbuilder: true
            # Permissions to grant to VIPs:
            command.weather: true
    mineground.moderator:
        description: All permissions available for moderators.
        children:
            mineground.vip: true
            # Permissions to grant to moderators:
            command.kick: true
            command.note: true
            command.notes: true
            command.weather.storm: true
            wrap.teleport_no_password: true
            warp.remove_all: true
    mineground.administrator:
        description: All permissions available for administrators.
        children:
            mineground.moderator: true
            # Permissions to grant to administrators:
            command.mode: true
            world.list: true
            world.warp: true
    mineground.management:
        description: All permissions available for Management members.
        children:
            mineground.administrator: true
            # Permissions to grant to Management members:
            world.classic: true
            world.create: true
            world.creative: true
            world.destroy: true
            world.set.animals: true
            world.set.difficulty: true
            world.set.mobs: true
            world.set.pvp: true
            world.set.rule: true
            world.set.readonly: true
            world.set.spawn: true
            world.survival: true

    # ----------------------------------------------------------------------------------------------
    # Administrator Manager - commands intended for administrating the server.
    # ----------------------------------------------------------------------------------------------
    command.kick:
        description: Allows you to forcefully disconnect a player using the /kick command.
        default: op
    command.note:
        description: Allows you to use /note to create a new note for a player's profile.
        default: op
    command.notes:
        description: Allows you to use the /notes command to read a player's notes.
        default: op

    # ----------------------------------------------------------------------------------------------
    # Communication Manager - allows players to communicate with staff and other players.
    # ----------------------------------------------------------------------------------------------
    command.pm:
        description: Allows you to use the /pm command.
        default: op
    command.reply:
        description: Allows you to quickly reply to a previously received message.
        default: op
    command.report:
        description: Allows you to report an incident to online staff members.
        default: op

    # ----------------------------------------------------------------------------------------------
    # Warp Manager - allows players to create warps, warp to them and share them with other players.
    # ----------------------------------------------------------------------------------------------
    warp.create:
        description: Allows you to create a new warp location.
        default: op
    warp.teleport:
        description: Allows you to teleport to warps of any player.
        default: op
    warp.teleport_no_password:
        description: Allows you to teleport to warps of any player without needing a password.
        default: op
    warp.remove:
        description: Allows you to remove your own warp locations.
        default: op
    warp.remove_all:
        description: Allows you to remove any warp location.
        default: op

    # ----------------------------------------------------------------------------------------------
    # World Manager - allows staff to manipulate the available worlds on Mineground.
    # ----------------------------------------------------------------------------------------------
    command.classic:
        description: Allows you to teleport to the classic world using /classic.
        default: op
    command.creative:
        description: Allows you to teleport to the creative world using /creative.
        default: op
    command.spawn:
        description: Allows you to teleport to the current world's spawn location.
        default: op
    command.survival:
        description: Allows you to teleport to the survival world using /survival.
        default: op
    world.classic:
        description: Allows you to change which world is known as the classic world.
        default: op
    world.create:
        description: Allows you to create new worlds on Mineground.
        default: op
    world.creative:
        description: Allows you to change which world is known as the creative world.
        default: op
    world.destroy:
        description: Allows you to destroy worlds which exist on Mineground.
        default: op
    world.list:
        description: Allows you to list existing worlds on Mineground.
        default: op
    world.set.animals:
        description: Allows you to change how many animals should spawn per chunk in a world.
        default: op
    world.set.difficulty:
        description: Allows you to change the difficulty of a world on Mineground.
        default: op
    world.set.mobs:
        description: Allows you to change how many mobs should spawn per chunk in a world.
        default: op
    world.set.pvp:
        description: Allows you to change whether player-versus-player fights are allowed.
        default: op
    world.set.readonly:
        description: Allows you to change whether a world is defined as read-only.
        default: op
    world.set.rule:
        description: Allows you to change more advanced game rules for a world.
        default: op
    world.set.spawn:
        description: Allows you to change the spawn position of any world.
        default: op
    world.survival:
        description: Allows you to change which world is known as the survival world.
        default: op
    world.warp:
        description: Allows you to warp to all available worlds on Mineground.
        default: op

    # ----------------------------------------------------------------------------------------------
    # General permissions, which don't belong to a specific feature.
    # ----------------------------------------------------------------------------------------------
    command.fly:
        description: Allows you to enable flying around in the current world.
        default: op
    command.mode:
        description: Allows you to change your game mode regardless of where you are.
        default: op
    command.weather:
        description: Allows you to change the weather using the /weather command.
        default: op
    command.weather.storm:
        description: Allows you to change the weather to storming using the /weather command.
        default: op


# The commands which are supported by the Mineground plugin.
commands:
    # ----------------------------------------------------------------------------------------------
    # AccountManager
    # ----------------------------------------------------------------------------------------------
    login:
        description: Identify yourself with your account.
        usage: /login [password]


    # ----------------------------------------------------------------------------------------------
    # Feature: Administrator Commands
    # ----------------------------------------------------------------------------------------------
    kick:
        description: Forcefully disconnects a player from Mineground.
        usage: /kick [player] [reason]
    note:
        description: Creates a note to be written to a player's profile.
        usage: /note [player] [message]
        aliases:
            - addnote
    notes:
        description: Displays the notes associated with a player.
        usage: /notes [player]
        aliases:
            - why


    # ----------------------------------------------------------------------------------------------
    # Feature: Communication Manager
    # ----------------------------------------------------------------------------------------------
    pm:
        description: Sends a private message to another player.
        usage: /pm [player] [message]
    reply:
        description: Replies to the player who last sent you a message.
        usage: /reply [message]
        aliases:
            - r
    report:
        description: Reports another player to online staff members.
        usage: /report [message]


    # ----------------------------------------------------------------------------------------------
    # Feature: Location Manager
    # ----------------------------------------------------------------------------------------------
    home:
        description: Teleports you directly back to your home.
        usage: /home [set]
    warp:
        description: Stores or teleports you to a location.
        usage: /warp [create/list/remove/NAME]


    # ----------------------------------------------------------------------------------------------
    # Feature: World Manager
    # ----------------------------------------------------------------------------------------------
    classic:
        description: Teleports you to the classic world.
        usage: /classic
    creative:
        description: Teleports you to the creative world.
        usage: /creative
    spawn:
        description: Teleports you back to this world's spawn.
        usage: /warp
    survival:
        description: Teleports you to the survival world.
        usage: /survival
    world:
        description: Manage the worlds available on Mineground.
        usage: /world

    # ----------------------------------------------------------------------------------------------
    # General commands
    # ----------------------------------------------------------------------------------------------
    fly:
        description: Enables you to fly around in the current world.
        usage: /fly [on/off]
    mode:
        description: Enables you to change your current gamemode.
        usage: /mode [player] [adventure, creative, survival]
    rules:
        description: Displays a list of Mineground's rules to you.
        usage: /rules
    staff:
        description: Displays a list of online staff members.
        usage: /staff
        aliases:
            - admins
    weather:
        description: Changes the weather in the current world.
        usage: /weather [sun/rain/storm]
